export default function Home() {
  return (
    <div className="contain">
      <p>root page1</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page</p>
      <p>root page last</p>
    </div>
  );
}
